# Generated by Django 4.2.7 on 2023-12-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_photofornews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oner_success',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sport_success',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
