# Generated by Django 4.2.7 on 2024-01-04 06:17

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_admin_school_alter_school_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_number',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school_socialmedia',
            name='type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('Youtube', 'Youtube')], default='Youtube', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='amount_of_family',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='amount_of_parents',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='number_of_10_11_classes',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='SchoolMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.FileField(upload_to='uploads/', validators=[main.models.validate_file_extension])),
                ('flat1', models.FileField(upload_to='uploads/', validators=[main.models.validate_file_extension])),
                ('flat2', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[main.models.validate_file_extension])),
                ('flat3', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[main.models.validate_file_extension])),
                ('flat4', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[main.models.validate_file_extension])),
                ('flat5', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[main.models.validate_file_extension])),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'SchoolMap',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('data', models.DateField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
