# Generated by Django 4.2.7 on 2024-01-05 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_class_class_number_alter_school_socialmedia_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='data',
        ),
        migrations.AddField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
